-- Insert common Brazilian university courses
-- These are predefined course names that users can select when creating courses
-- Users will only need to specify the number of semesters for each course
INSERT INTO cursos (nome, descricao, duracao_semestres) VALUES
('Administração', 'Curso de graduação em Administração', 8),
('Análise e Desenvolvimento de Sistemas', 'Curso de graduação em Análise e Desenvolvimento de Sistemas', 6),
('Arquitetura e Urbanismo', 'Curso de graduação em Arquitetura e Urbanismo', 10),
('Biomedicina', 'Curso de graduação em Biomedicina', 8),
('Cinema e Audiovisual', 'Curso de graduação em Cinema e Audiovisual', 8),
('Ciência da Computação', 'Curso de graduação em Ciência da Computação', 8),
('Ciências Contábeis', 'Curso de graduação em Ciências Contábeis', 8),
('Ciências Econômicas', 'Curso de graduação em Ciências Econômicas', 8),
('Comércio Exterior', 'Curso de graduação em Comércio Exterior', 6),
('Design de Interiores', 'Curso de graduação em Design de Interiores', 6),
('Design de Moda', 'Curso de graduação em Design de Moda', 8),
('Direito', 'Curso de graduação em Direito', 10),
('Educação Física', 'Curso de graduação em Educação Física', 8),
('Enfermagem', 'Curso de graduação em Enfermagem', 8),
('Engenharia Civil', 'Curso de graduação em Engenharia Civil', 10),
('Engenharia de Controle e Automação', 'Curso de graduação em Engenharia de Controle e Automação', 10),
('Engenharia de Produção', 'Curso de graduação em Engenharia de Produção', 10),
('Engenharia Elétrica', 'Curso de graduação em Engenharia Elétrica', 10),
('Engenharia Mecânica', 'Curso de graduação em Engenharia Mecânica', 10),
('Engenharia Urbana e Ambiental', 'Curso de graduação em Engenharia Urbana e Ambiental', 10),
('Estética e Cosmética', 'Curso de graduação em Estética e Cosmética', 6),
('Farmácia', 'Curso de graduação em Farmácia', 10),
('Finanças', 'Curso de graduação em Finanças', 6),
('Fisioterapia', 'Curso de graduação em Fisioterapia', 10),
('Gastronomia', 'Curso de graduação em Gastronomia', 6),
('Gestão de Recursos Humanos', 'Curso de graduação em Gestão de Recursos Humanos', 6),
('Jornalismo', 'Curso de graduação em Jornalismo', 8),
('Logística', 'Curso de graduação em Logística', 6),
('Marketing', 'Curso de graduação em Marketing', 6),
('Medicina', 'Curso de graduação em Medicina', 12),
('Medicina Veterinária', 'Curso de graduação em Medicina Veterinária', 10),
('Moda', 'Curso de graduação em Moda', 8),
('Negócios', 'Curso de graduação em Negócios', 6),
('Nutrição', 'Curso de graduação em Nutrição', 8),
('Odontologia', 'Curso de graduação em Odontologia', 10),
('Psicologia', 'Curso de graduação em Psicologia', 10),
('Publicidade e Propaganda', 'Curso de graduação em Publicidade e Propaganda', 8),
('Sistemas de Informação', 'Curso de graduação em Sistemas de Informação', 8),
('Turismo', 'Curso de graduação em Turismo', 6);
