apiVersion: apps/v1
kind: Deployment
metadata:
  name: grades-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grades-service
  template:
    metadata:
      labels:
        app: grades-service
    spec:
      containers:
      - name: grades-service
        image: distrischool-grades-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres-service:5432/distrischool_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "postgres"
        - name: SPRING_RABBITMQ_HOST
          value: "rabbitmq-service"
        - name: SPRING_RABBITMQ_PORT
          value: "5672"
        - name: SPRING_RABBITMQ_USERNAME
          value: "guest"
        - name: SPRING_RABBITMQ_PASSWORD
          value: "guest"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA
          value: "grades_schema"
        - name: SPRING_FLYWAY_SCHEMAS
          value: "grades_schema"
        - name: SPRING_FLYWAY_CREATE_SCHEMAS
          value: "true"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8083
          initialDelaySeconds: 60
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: grades-service
spec:
  selector:
    app: grades-service
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083
  type: ClusterIP
